"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const analytics_controller_1 = require("../controllers/analytics.controller");
const auth_middleware_1 = require("../middleware/auth.middleware");
const authorize_middleware_1 = require("../middleware/authorize.middleware");
const permissions_middleware_1 = require("../middleware/permissions.middleware");
const router = (0, express_1.Router)();
const c = new analytics_controller_1.AnalyticsController();
router.use(auth_middleware_1.authMiddleware);
router.get('/finance/opex', (0, permissions_middleware_1.requireOfficePermission)('analytics_finance', 'read'), c.finance.bind(c));
router.get('/finance/daily', (0, permissions_middleware_1.requireOfficePermission)('analytics_finance', 'read'), c.financeDaily.bind(c));
router.get('/export/orders', (0, permissions_middleware_1.requireOfficePermission)('analytics_finance', 'write'), c.exportOrders.bind(c));
router.use(authorize_middleware_1.requireOfficeStaff);
router.get('/summary', c.summary.bind(c));
router.get('/peaks', c.peaks.bind(c));
router.get('/routes/efficiency', c.routes.bind(c));
router.get('/traffic/grid', c.traffic.bind(c));
router.get('/demand/hourly', c.demandSeries.bind(c));
router.get('/demand/peaks', c.peaksDetected.bind(c));
router.get('/demand/forecast', c.forecast.bind(c));
router.get('/surge/timeseries', c.surge.bind(c));
router.get('/geo/pickup-grid', c.pickupGrid.bind(c));
router.get('/fleet/driver-kpis', c.driverKpis.bind(c));
router.post('/maintenance', authorize_middleware_1.requireOperationsStaff, c.createMaintenance.bind(c));
router.get('/maintenance/vehicle/:vehicleId', authorize_middleware_1.requireOperationsStaff, c.listMaintenance.bind(c));
router.post('/payroll', (0, permissions_middleware_1.requireOfficePermission)('analytics_finance', 'write'), c.createPayroll.bind(c));
router.post('/operating-expenses', (0, permissions_middleware_1.requireOfficePermission)('analytics_finance', 'write'), c.createOperatingExpense.bind(c));
exports.default = router;
//# sourceMappingURL=analytics.routes.js.map