import { Prisma } from '@prisma/client';
export declare class TransactionService {
    create(data: Prisma.TransactionCreateInput): Promise<{
        order: {
            id: string;
            driverId: string | null;
            createdAt: Date;
            updatedAt: Date;
            status: import(".prisma/client").$Enums.OrderStatus;
            clientId: string;
            tariffId: string;
            pickupAddress: string;
            pickupLat: number;
            pickupLng: number;
            dropoffAddress: string;
            dropoffLat: number;
            dropoffLng: number;
            distanceKm: number;
            totalPrice: Prisma.Decimal;
            paymentMethod: import(".prisma/client").$Enums.PaymentMethod;
            surgeMultiplier: number;
            clientPreferences: Prisma.JsonValue | null;
            promoCode: string | null;
            plannedRouteDistanceKm: number | null;
            plannedRouteDurationMin: number | null;
            plannedRoutePolyline: Prisma.JsonValue | null;
            navigationRouteToPickup: Prisma.JsonValue | null;
            navigationRouteToDropoff: Prisma.JsonValue | null;
            actualRouteDistanceKm: number | null;
            platformFeeAmount: Prisma.Decimal | null;
            driverEarningAmount: Prisma.Decimal | null;
            matchDeadlineAt: Date | null;
            deliverySenderName: string | null;
            deliverySenderPhone: string | null;
            deliveryRecipientName: string | null;
            deliveryRecipientPhone: string | null;
            deliveryPayer: import(".prisma/client").$Enums.DeliveryPayer | null;
            preferredDriverUserId: string | null;
            dispatcherNotes: string | null;
            cancelledByRole: import(".prisma/client").$Enums.Role | null;
            cancellationReason: import(".prisma/client").$Enums.CancellationReason | null;
            startedAt: Date | null;
            finishedAt: Date | null;
        } | null;
        driver: {
            id: string;
            userId: string;
            licenseNumber: string;
            status: import(".prisma/client").$Enums.DriverStatus;
            balance: Prisma.Decimal;
            currentLat: number | null;
            currentLng: number | null;
            lastActive: Date;
            verificationStatus: import(".prisma/client").$Enums.DriverVerificationStatus;
        };
    } & {
        id: string;
        driverId: string;
        createdAt: Date;
        orderId: string | null;
        amount: Prisma.Decimal;
        type: string;
    }>;
    findAll(): Promise<({
        order: {
            id: string;
            driverId: string | null;
            createdAt: Date;
            updatedAt: Date;
            status: import(".prisma/client").$Enums.OrderStatus;
            clientId: string;
            tariffId: string;
            pickupAddress: string;
            pickupLat: number;
            pickupLng: number;
            dropoffAddress: string;
            dropoffLat: number;
            dropoffLng: number;
            distanceKm: number;
            totalPrice: Prisma.Decimal;
            paymentMethod: import(".prisma/client").$Enums.PaymentMethod;
            surgeMultiplier: number;
            clientPreferences: Prisma.JsonValue | null;
            promoCode: string | null;
            plannedRouteDistanceKm: number | null;
            plannedRouteDurationMin: number | null;
            plannedRoutePolyline: Prisma.JsonValue | null;
            navigationRouteToPickup: Prisma.JsonValue | null;
            navigationRouteToDropoff: Prisma.JsonValue | null;
            actualRouteDistanceKm: number | null;
            platformFeeAmount: Prisma.Decimal | null;
            driverEarningAmount: Prisma.Decimal | null;
            matchDeadlineAt: Date | null;
            deliverySenderName: string | null;
            deliverySenderPhone: string | null;
            deliveryRecipientName: string | null;
            deliveryRecipientPhone: string | null;
            deliveryPayer: import(".prisma/client").$Enums.DeliveryPayer | null;
            preferredDriverUserId: string | null;
            dispatcherNotes: string | null;
            cancelledByRole: import(".prisma/client").$Enums.Role | null;
            cancellationReason: import(".prisma/client").$Enums.CancellationReason | null;
            startedAt: Date | null;
            finishedAt: Date | null;
        } | null;
        driver: {
            user: {
                id: string;
                role: import(".prisma/client").$Enums.Role;
                username: string | null;
                phone: string;
                email: string | null;
                password: string;
                fullName: string;
                avatarUrl: string | null;
                officeRoleId: string | null;
                rating: number;
                pushToken: string | null;
                createdAt: Date;
                updatedAt: Date;
            };
        } & {
            id: string;
            userId: string;
            licenseNumber: string;
            status: import(".prisma/client").$Enums.DriverStatus;
            balance: Prisma.Decimal;
            currentLat: number | null;
            currentLng: number | null;
            lastActive: Date;
            verificationStatus: import(".prisma/client").$Enums.DriverVerificationStatus;
        };
    } & {
        id: string;
        driverId: string;
        createdAt: Date;
        orderId: string | null;
        amount: Prisma.Decimal;
        type: string;
    })[]>;
    findByDriverId(driverId: string): Promise<{
        id: string;
        driverId: string;
        createdAt: Date;
        orderId: string | null;
        amount: Prisma.Decimal;
        type: string;
    }[]>;
    findById(id: string): Promise<({
        order: {
            id: string;
            driverId: string | null;
            createdAt: Date;
            updatedAt: Date;
            status: import(".prisma/client").$Enums.OrderStatus;
            clientId: string;
            tariffId: string;
            pickupAddress: string;
            pickupLat: number;
            pickupLng: number;
            dropoffAddress: string;
            dropoffLat: number;
            dropoffLng: number;
            distanceKm: number;
            totalPrice: Prisma.Decimal;
            paymentMethod: import(".prisma/client").$Enums.PaymentMethod;
            surgeMultiplier: number;
            clientPreferences: Prisma.JsonValue | null;
            promoCode: string | null;
            plannedRouteDistanceKm: number | null;
            plannedRouteDurationMin: number | null;
            plannedRoutePolyline: Prisma.JsonValue | null;
            navigationRouteToPickup: Prisma.JsonValue | null;
            navigationRouteToDropoff: Prisma.JsonValue | null;
            actualRouteDistanceKm: number | null;
            platformFeeAmount: Prisma.Decimal | null;
            driverEarningAmount: Prisma.Decimal | null;
            matchDeadlineAt: Date | null;
            deliverySenderName: string | null;
            deliverySenderPhone: string | null;
            deliveryRecipientName: string | null;
            deliveryRecipientPhone: string | null;
            deliveryPayer: import(".prisma/client").$Enums.DeliveryPayer | null;
            preferredDriverUserId: string | null;
            dispatcherNotes: string | null;
            cancelledByRole: import(".prisma/client").$Enums.Role | null;
            cancellationReason: import(".prisma/client").$Enums.CancellationReason | null;
            startedAt: Date | null;
            finishedAt: Date | null;
        } | null;
        driver: {
            id: string;
            userId: string;
            licenseNumber: string;
            status: import(".prisma/client").$Enums.DriverStatus;
            balance: Prisma.Decimal;
            currentLat: number | null;
            currentLng: number | null;
            lastActive: Date;
            verificationStatus: import(".prisma/client").$Enums.DriverVerificationStatus;
        };
    } & {
        id: string;
        driverId: string;
        createdAt: Date;
        orderId: string | null;
        amount: Prisma.Decimal;
        type: string;
    }) | null>;
}
//# sourceMappingURL=transaction.service.d.ts.map